" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=b

set noundofile
set nobackup

set langmenu=en_US.UTF-8
let $LANG='en'
language en

set syntax=on
set t_Co=256
" set background=dark
colorscheme retrobox
set guifont=consolas:h9

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent

set list
set listchars=tab:>-,trail:·,space:·

set number
set enc=utf-8
set showmatch
set noswapfile
set clipboard=unnamedplus

set cursorline
" highlight CursorLine ctermbg=234 guibg=#1c1c1c
highlight LineNr ctermfg=grey guifg=grey

" highlight Comment ctermfg=lightblue guifg=lightblue
highlight Normal ctermfg=grey guifg=grey

set showcmd

set laststatus=2
set statusline=%#PStatusLine#
set statusline+=%f                           " 文件名
set statusline+=%h                           " 帮助文件标志
set statusline+=%m                           " 修改标志
set statusline+=%r                           " 只读标志
set statusline+=%=                           " 分隔符，将左对齐和右对齐的部分分开
set statusline+=%#PStatusLineMode#%{mode()}  " 模式
set statusline+=%#PStatusLine#
set statusline+=\ %y                         " 文件类型
set statusline+=\ [%{&fileencoding}]         " 文件编码
set statusline+=\ %l/%L,%c                   " 当前行号和列号
set statusline+=\ %P                         " 文件百分比
highlight PStatusLine ctermfg=black ctermbg=yellow guifg=black guibg=yellow
highlight PStatusLineMode ctermfg=black ctermbg=cyan guifg=black guibg=cyan
